#pragma once
// Auto-generated by tools/gen_boot_anim.py from assets/boot_anim_source.mp4 -- do not hand-edit.
// Frame bytes are linked in from main/boot_anim_frames/*.jpg via EMBED_FILES (main/CMakeLists.txt), not stored here.
#include <cstdint>
#include <cstddef>

extern "C" {
extern const uint8_t frame0001_jpg_start[] asm("_binary_frame0001_jpg_start");
extern const uint8_t frame0001_jpg_end[]   asm("_binary_frame0001_jpg_end");
extern const uint8_t frame0002_jpg_start[] asm("_binary_frame0002_jpg_start");
extern const uint8_t frame0002_jpg_end[]   asm("_binary_frame0002_jpg_end");
extern const uint8_t frame0003_jpg_start[] asm("_binary_frame0003_jpg_start");
extern const uint8_t frame0003_jpg_end[]   asm("_binary_frame0003_jpg_end");
extern const uint8_t frame0004_jpg_start[] asm("_binary_frame0004_jpg_start");
extern const uint8_t frame0004_jpg_end[]   asm("_binary_frame0004_jpg_end");
extern const uint8_t frame0005_jpg_start[] asm("_binary_frame0005_jpg_start");
extern const uint8_t frame0005_jpg_end[]   asm("_binary_frame0005_jpg_end");
extern const uint8_t frame0006_jpg_start[] asm("_binary_frame0006_jpg_start");
extern const uint8_t frame0006_jpg_end[]   asm("_binary_frame0006_jpg_end");
extern const uint8_t frame0007_jpg_start[] asm("_binary_frame0007_jpg_start");
extern const uint8_t frame0007_jpg_end[]   asm("_binary_frame0007_jpg_end");
extern const uint8_t frame0008_jpg_start[] asm("_binary_frame0008_jpg_start");
extern const uint8_t frame0008_jpg_end[]   asm("_binary_frame0008_jpg_end");
extern const uint8_t frame0009_jpg_start[] asm("_binary_frame0009_jpg_start");
extern const uint8_t frame0009_jpg_end[]   asm("_binary_frame0009_jpg_end");
extern const uint8_t frame0010_jpg_start[] asm("_binary_frame0010_jpg_start");
extern const uint8_t frame0010_jpg_end[]   asm("_binary_frame0010_jpg_end");
extern const uint8_t frame0011_jpg_start[] asm("_binary_frame0011_jpg_start");
extern const uint8_t frame0011_jpg_end[]   asm("_binary_frame0011_jpg_end");
extern const uint8_t frame0012_jpg_start[] asm("_binary_frame0012_jpg_start");
extern const uint8_t frame0012_jpg_end[]   asm("_binary_frame0012_jpg_end");
extern const uint8_t frame0013_jpg_start[] asm("_binary_frame0013_jpg_start");
extern const uint8_t frame0013_jpg_end[]   asm("_binary_frame0013_jpg_end");
extern const uint8_t frame0014_jpg_start[] asm("_binary_frame0014_jpg_start");
extern const uint8_t frame0014_jpg_end[]   asm("_binary_frame0014_jpg_end");
extern const uint8_t frame0015_jpg_start[] asm("_binary_frame0015_jpg_start");
extern const uint8_t frame0015_jpg_end[]   asm("_binary_frame0015_jpg_end");
extern const uint8_t frame0016_jpg_start[] asm("_binary_frame0016_jpg_start");
extern const uint8_t frame0016_jpg_end[]   asm("_binary_frame0016_jpg_end");
extern const uint8_t frame0017_jpg_start[] asm("_binary_frame0017_jpg_start");
extern const uint8_t frame0017_jpg_end[]   asm("_binary_frame0017_jpg_end");
extern const uint8_t frame0018_jpg_start[] asm("_binary_frame0018_jpg_start");
extern const uint8_t frame0018_jpg_end[]   asm("_binary_frame0018_jpg_end");
extern const uint8_t frame0019_jpg_start[] asm("_binary_frame0019_jpg_start");
extern const uint8_t frame0019_jpg_end[]   asm("_binary_frame0019_jpg_end");
extern const uint8_t frame0020_jpg_start[] asm("_binary_frame0020_jpg_start");
extern const uint8_t frame0020_jpg_end[]   asm("_binary_frame0020_jpg_end");
extern const uint8_t frame0021_jpg_start[] asm("_binary_frame0021_jpg_start");
extern const uint8_t frame0021_jpg_end[]   asm("_binary_frame0021_jpg_end");
extern const uint8_t frame0022_jpg_start[] asm("_binary_frame0022_jpg_start");
extern const uint8_t frame0022_jpg_end[]   asm("_binary_frame0022_jpg_end");
extern const uint8_t frame0023_jpg_start[] asm("_binary_frame0023_jpg_start");
extern const uint8_t frame0023_jpg_end[]   asm("_binary_frame0023_jpg_end");
extern const uint8_t frame0024_jpg_start[] asm("_binary_frame0024_jpg_start");
extern const uint8_t frame0024_jpg_end[]   asm("_binary_frame0024_jpg_end");
extern const uint8_t frame0025_jpg_start[] asm("_binary_frame0025_jpg_start");
extern const uint8_t frame0025_jpg_end[]   asm("_binary_frame0025_jpg_end");
extern const uint8_t frame0026_jpg_start[] asm("_binary_frame0026_jpg_start");
extern const uint8_t frame0026_jpg_end[]   asm("_binary_frame0026_jpg_end");
extern const uint8_t frame0027_jpg_start[] asm("_binary_frame0027_jpg_start");
extern const uint8_t frame0027_jpg_end[]   asm("_binary_frame0027_jpg_end");
extern const uint8_t frame0028_jpg_start[] asm("_binary_frame0028_jpg_start");
extern const uint8_t frame0028_jpg_end[]   asm("_binary_frame0028_jpg_end");
extern const uint8_t frame0029_jpg_start[] asm("_binary_frame0029_jpg_start");
extern const uint8_t frame0029_jpg_end[]   asm("_binary_frame0029_jpg_end");
extern const uint8_t frame0030_jpg_start[] asm("_binary_frame0030_jpg_start");
extern const uint8_t frame0030_jpg_end[]   asm("_binary_frame0030_jpg_end");
extern const uint8_t frame0031_jpg_start[] asm("_binary_frame0031_jpg_start");
extern const uint8_t frame0031_jpg_end[]   asm("_binary_frame0031_jpg_end");
extern const uint8_t frame0032_jpg_start[] asm("_binary_frame0032_jpg_start");
extern const uint8_t frame0032_jpg_end[]   asm("_binary_frame0032_jpg_end");
extern const uint8_t frame0033_jpg_start[] asm("_binary_frame0033_jpg_start");
extern const uint8_t frame0033_jpg_end[]   asm("_binary_frame0033_jpg_end");
extern const uint8_t frame0034_jpg_start[] asm("_binary_frame0034_jpg_start");
extern const uint8_t frame0034_jpg_end[]   asm("_binary_frame0034_jpg_end");
extern const uint8_t frame0035_jpg_start[] asm("_binary_frame0035_jpg_start");
extern const uint8_t frame0035_jpg_end[]   asm("_binary_frame0035_jpg_end");
extern const uint8_t frame0036_jpg_start[] asm("_binary_frame0036_jpg_start");
extern const uint8_t frame0036_jpg_end[]   asm("_binary_frame0036_jpg_end");
extern const uint8_t frame0037_jpg_start[] asm("_binary_frame0037_jpg_start");
extern const uint8_t frame0037_jpg_end[]   asm("_binary_frame0037_jpg_end");
extern const uint8_t frame0038_jpg_start[] asm("_binary_frame0038_jpg_start");
extern const uint8_t frame0038_jpg_end[]   asm("_binary_frame0038_jpg_end");
extern const uint8_t frame0039_jpg_start[] asm("_binary_frame0039_jpg_start");
extern const uint8_t frame0039_jpg_end[]   asm("_binary_frame0039_jpg_end");
extern const uint8_t frame0040_jpg_start[] asm("_binary_frame0040_jpg_start");
extern const uint8_t frame0040_jpg_end[]   asm("_binary_frame0040_jpg_end");
extern const uint8_t frame0041_jpg_start[] asm("_binary_frame0041_jpg_start");
extern const uint8_t frame0041_jpg_end[]   asm("_binary_frame0041_jpg_end");
extern const uint8_t frame0042_jpg_start[] asm("_binary_frame0042_jpg_start");
extern const uint8_t frame0042_jpg_end[]   asm("_binary_frame0042_jpg_end");
extern const uint8_t frame0043_jpg_start[] asm("_binary_frame0043_jpg_start");
extern const uint8_t frame0043_jpg_end[]   asm("_binary_frame0043_jpg_end");
extern const uint8_t frame0044_jpg_start[] asm("_binary_frame0044_jpg_start");
extern const uint8_t frame0044_jpg_end[]   asm("_binary_frame0044_jpg_end");
extern const uint8_t frame0045_jpg_start[] asm("_binary_frame0045_jpg_start");
extern const uint8_t frame0045_jpg_end[]   asm("_binary_frame0045_jpg_end");
extern const uint8_t frame0046_jpg_start[] asm("_binary_frame0046_jpg_start");
extern const uint8_t frame0046_jpg_end[]   asm("_binary_frame0046_jpg_end");
extern const uint8_t frame0047_jpg_start[] asm("_binary_frame0047_jpg_start");
extern const uint8_t frame0047_jpg_end[]   asm("_binary_frame0047_jpg_end");
extern const uint8_t frame0048_jpg_start[] asm("_binary_frame0048_jpg_start");
extern const uint8_t frame0048_jpg_end[]   asm("_binary_frame0048_jpg_end");
extern const uint8_t frame0049_jpg_start[] asm("_binary_frame0049_jpg_start");
extern const uint8_t frame0049_jpg_end[]   asm("_binary_frame0049_jpg_end");
extern const uint8_t frame0050_jpg_start[] asm("_binary_frame0050_jpg_start");
extern const uint8_t frame0050_jpg_end[]   asm("_binary_frame0050_jpg_end");
extern const uint8_t frame0051_jpg_start[] asm("_binary_frame0051_jpg_start");
extern const uint8_t frame0051_jpg_end[]   asm("_binary_frame0051_jpg_end");
extern const uint8_t frame0052_jpg_start[] asm("_binary_frame0052_jpg_start");
extern const uint8_t frame0052_jpg_end[]   asm("_binary_frame0052_jpg_end");
extern const uint8_t frame0053_jpg_start[] asm("_binary_frame0053_jpg_start");
extern const uint8_t frame0053_jpg_end[]   asm("_binary_frame0053_jpg_end");
extern const uint8_t frame0054_jpg_start[] asm("_binary_frame0054_jpg_start");
extern const uint8_t frame0054_jpg_end[]   asm("_binary_frame0054_jpg_end");
extern const uint8_t frame0055_jpg_start[] asm("_binary_frame0055_jpg_start");
extern const uint8_t frame0055_jpg_end[]   asm("_binary_frame0055_jpg_end");
extern const uint8_t frame0056_jpg_start[] asm("_binary_frame0056_jpg_start");
extern const uint8_t frame0056_jpg_end[]   asm("_binary_frame0056_jpg_end");
extern const uint8_t frame0057_jpg_start[] asm("_binary_frame0057_jpg_start");
extern const uint8_t frame0057_jpg_end[]   asm("_binary_frame0057_jpg_end");
extern const uint8_t frame0058_jpg_start[] asm("_binary_frame0058_jpg_start");
extern const uint8_t frame0058_jpg_end[]   asm("_binary_frame0058_jpg_end");
extern const uint8_t frame0059_jpg_start[] asm("_binary_frame0059_jpg_start");
extern const uint8_t frame0059_jpg_end[]   asm("_binary_frame0059_jpg_end");
extern const uint8_t frame0060_jpg_start[] asm("_binary_frame0060_jpg_start");
extern const uint8_t frame0060_jpg_end[]   asm("_binary_frame0060_jpg_end");
extern const uint8_t frame0061_jpg_start[] asm("_binary_frame0061_jpg_start");
extern const uint8_t frame0061_jpg_end[]   asm("_binary_frame0061_jpg_end");
extern const uint8_t frame0062_jpg_start[] asm("_binary_frame0062_jpg_start");
extern const uint8_t frame0062_jpg_end[]   asm("_binary_frame0062_jpg_end");
extern const uint8_t frame0063_jpg_start[] asm("_binary_frame0063_jpg_start");
extern const uint8_t frame0063_jpg_end[]   asm("_binary_frame0063_jpg_end");
extern const uint8_t frame0064_jpg_start[] asm("_binary_frame0064_jpg_start");
extern const uint8_t frame0064_jpg_end[]   asm("_binary_frame0064_jpg_end");
extern const uint8_t frame0065_jpg_start[] asm("_binary_frame0065_jpg_start");
extern const uint8_t frame0065_jpg_end[]   asm("_binary_frame0065_jpg_end");
extern const uint8_t frame0066_jpg_start[] asm("_binary_frame0066_jpg_start");
extern const uint8_t frame0066_jpg_end[]   asm("_binary_frame0066_jpg_end");
extern const uint8_t frame0067_jpg_start[] asm("_binary_frame0067_jpg_start");
extern const uint8_t frame0067_jpg_end[]   asm("_binary_frame0067_jpg_end");
extern const uint8_t frame0068_jpg_start[] asm("_binary_frame0068_jpg_start");
extern const uint8_t frame0068_jpg_end[]   asm("_binary_frame0068_jpg_end");
extern const uint8_t frame0069_jpg_start[] asm("_binary_frame0069_jpg_start");
extern const uint8_t frame0069_jpg_end[]   asm("_binary_frame0069_jpg_end");
extern const uint8_t frame0070_jpg_start[] asm("_binary_frame0070_jpg_start");
extern const uint8_t frame0070_jpg_end[]   asm("_binary_frame0070_jpg_end");
extern const uint8_t frame0071_jpg_start[] asm("_binary_frame0071_jpg_start");
extern const uint8_t frame0071_jpg_end[]   asm("_binary_frame0071_jpg_end");
extern const uint8_t frame0072_jpg_start[] asm("_binary_frame0072_jpg_start");
extern const uint8_t frame0072_jpg_end[]   asm("_binary_frame0072_jpg_end");
extern const uint8_t frame0073_jpg_start[] asm("_binary_frame0073_jpg_start");
extern const uint8_t frame0073_jpg_end[]   asm("_binary_frame0073_jpg_end");
extern const uint8_t frame0074_jpg_start[] asm("_binary_frame0074_jpg_start");
extern const uint8_t frame0074_jpg_end[]   asm("_binary_frame0074_jpg_end");
extern const uint8_t frame0075_jpg_start[] asm("_binary_frame0075_jpg_start");
extern const uint8_t frame0075_jpg_end[]   asm("_binary_frame0075_jpg_end");
extern const uint8_t frame0076_jpg_start[] asm("_binary_frame0076_jpg_start");
extern const uint8_t frame0076_jpg_end[]   asm("_binary_frame0076_jpg_end");
extern const uint8_t frame0077_jpg_start[] asm("_binary_frame0077_jpg_start");
extern const uint8_t frame0077_jpg_end[]   asm("_binary_frame0077_jpg_end");
extern const uint8_t frame0078_jpg_start[] asm("_binary_frame0078_jpg_start");
extern const uint8_t frame0078_jpg_end[]   asm("_binary_frame0078_jpg_end");
extern const uint8_t frame0079_jpg_start[] asm("_binary_frame0079_jpg_start");
extern const uint8_t frame0079_jpg_end[]   asm("_binary_frame0079_jpg_end");
extern const uint8_t frame0080_jpg_start[] asm("_binary_frame0080_jpg_start");
extern const uint8_t frame0080_jpg_end[]   asm("_binary_frame0080_jpg_end");
}

struct BootAnimFrame { const uint8_t* data; size_t len; };

constexpr int BOOT_ANIM_FRAME_COUNT = 80;
constexpr int BOOT_ANIM_FPS = 8;

const BootAnimFrame BOOT_ANIM_FRAMES[BOOT_ANIM_FRAME_COUNT] = {
    { frame0001_jpg_start, (size_t)(frame0001_jpg_end - frame0001_jpg_start) },
    { frame0002_jpg_start, (size_t)(frame0002_jpg_end - frame0002_jpg_start) },
    { frame0003_jpg_start, (size_t)(frame0003_jpg_end - frame0003_jpg_start) },
    { frame0004_jpg_start, (size_t)(frame0004_jpg_end - frame0004_jpg_start) },
    { frame0005_jpg_start, (size_t)(frame0005_jpg_end - frame0005_jpg_start) },
    { frame0006_jpg_start, (size_t)(frame0006_jpg_end - frame0006_jpg_start) },
    { frame0007_jpg_start, (size_t)(frame0007_jpg_end - frame0007_jpg_start) },
    { frame0008_jpg_start, (size_t)(frame0008_jpg_end - frame0008_jpg_start) },
    { frame0009_jpg_start, (size_t)(frame0009_jpg_end - frame0009_jpg_start) },
    { frame0010_jpg_start, (size_t)(frame0010_jpg_end - frame0010_jpg_start) },
    { frame0011_jpg_start, (size_t)(frame0011_jpg_end - frame0011_jpg_start) },
    { frame0012_jpg_start, (size_t)(frame0012_jpg_end - frame0012_jpg_start) },
    { frame0013_jpg_start, (size_t)(frame0013_jpg_end - frame0013_jpg_start) },
    { frame0014_jpg_start, (size_t)(frame0014_jpg_end - frame0014_jpg_start) },
    { frame0015_jpg_start, (size_t)(frame0015_jpg_end - frame0015_jpg_start) },
    { frame0016_jpg_start, (size_t)(frame0016_jpg_end - frame0016_jpg_start) },
    { frame0017_jpg_start, (size_t)(frame0017_jpg_end - frame0017_jpg_start) },
    { frame0018_jpg_start, (size_t)(frame0018_jpg_end - frame0018_jpg_start) },
    { frame0019_jpg_start, (size_t)(frame0019_jpg_end - frame0019_jpg_start) },
    { frame0020_jpg_start, (size_t)(frame0020_jpg_end - frame0020_jpg_start) },
    { frame0021_jpg_start, (size_t)(frame0021_jpg_end - frame0021_jpg_start) },
    { frame0022_jpg_start, (size_t)(frame0022_jpg_end - frame0022_jpg_start) },
    { frame0023_jpg_start, (size_t)(frame0023_jpg_end - frame0023_jpg_start) },
    { frame0024_jpg_start, (size_t)(frame0024_jpg_end - frame0024_jpg_start) },
    { frame0025_jpg_start, (size_t)(frame0025_jpg_end - frame0025_jpg_start) },
    { frame0026_jpg_start, (size_t)(frame0026_jpg_end - frame0026_jpg_start) },
    { frame0027_jpg_start, (size_t)(frame0027_jpg_end - frame0027_jpg_start) },
    { frame0028_jpg_start, (size_t)(frame0028_jpg_end - frame0028_jpg_start) },
    { frame0029_jpg_start, (size_t)(frame0029_jpg_end - frame0029_jpg_start) },
    { frame0030_jpg_start, (size_t)(frame0030_jpg_end - frame0030_jpg_start) },
    { frame0031_jpg_start, (size_t)(frame0031_jpg_end - frame0031_jpg_start) },
    { frame0032_jpg_start, (size_t)(frame0032_jpg_end - frame0032_jpg_start) },
    { frame0033_jpg_start, (size_t)(frame0033_jpg_end - frame0033_jpg_start) },
    { frame0034_jpg_start, (size_t)(frame0034_jpg_end - frame0034_jpg_start) },
    { frame0035_jpg_start, (size_t)(frame0035_jpg_end - frame0035_jpg_start) },
    { frame0036_jpg_start, (size_t)(frame0036_jpg_end - frame0036_jpg_start) },
    { frame0037_jpg_start, (size_t)(frame0037_jpg_end - frame0037_jpg_start) },
    { frame0038_jpg_start, (size_t)(frame0038_jpg_end - frame0038_jpg_start) },
    { frame0039_jpg_start, (size_t)(frame0039_jpg_end - frame0039_jpg_start) },
    { frame0040_jpg_start, (size_t)(frame0040_jpg_end - frame0040_jpg_start) },
    { frame0041_jpg_start, (size_t)(frame0041_jpg_end - frame0041_jpg_start) },
    { frame0042_jpg_start, (size_t)(frame0042_jpg_end - frame0042_jpg_start) },
    { frame0043_jpg_start, (size_t)(frame0043_jpg_end - frame0043_jpg_start) },
    { frame0044_jpg_start, (size_t)(frame0044_jpg_end - frame0044_jpg_start) },
    { frame0045_jpg_start, (size_t)(frame0045_jpg_end - frame0045_jpg_start) },
    { frame0046_jpg_start, (size_t)(frame0046_jpg_end - frame0046_jpg_start) },
    { frame0047_jpg_start, (size_t)(frame0047_jpg_end - frame0047_jpg_start) },
    { frame0048_jpg_start, (size_t)(frame0048_jpg_end - frame0048_jpg_start) },
    { frame0049_jpg_start, (size_t)(frame0049_jpg_end - frame0049_jpg_start) },
    { frame0050_jpg_start, (size_t)(frame0050_jpg_end - frame0050_jpg_start) },
    { frame0051_jpg_start, (size_t)(frame0051_jpg_end - frame0051_jpg_start) },
    { frame0052_jpg_start, (size_t)(frame0052_jpg_end - frame0052_jpg_start) },
    { frame0053_jpg_start, (size_t)(frame0053_jpg_end - frame0053_jpg_start) },
    { frame0054_jpg_start, (size_t)(frame0054_jpg_end - frame0054_jpg_start) },
    { frame0055_jpg_start, (size_t)(frame0055_jpg_end - frame0055_jpg_start) },
    { frame0056_jpg_start, (size_t)(frame0056_jpg_end - frame0056_jpg_start) },
    { frame0057_jpg_start, (size_t)(frame0057_jpg_end - frame0057_jpg_start) },
    { frame0058_jpg_start, (size_t)(frame0058_jpg_end - frame0058_jpg_start) },
    { frame0059_jpg_start, (size_t)(frame0059_jpg_end - frame0059_jpg_start) },
    { frame0060_jpg_start, (size_t)(frame0060_jpg_end - frame0060_jpg_start) },
    { frame0061_jpg_start, (size_t)(frame0061_jpg_end - frame0061_jpg_start) },
    { frame0062_jpg_start, (size_t)(frame0062_jpg_end - frame0062_jpg_start) },
    { frame0063_jpg_start, (size_t)(frame0063_jpg_end - frame0063_jpg_start) },
    { frame0064_jpg_start, (size_t)(frame0064_jpg_end - frame0064_jpg_start) },
    { frame0065_jpg_start, (size_t)(frame0065_jpg_end - frame0065_jpg_start) },
    { frame0066_jpg_start, (size_t)(frame0066_jpg_end - frame0066_jpg_start) },
    { frame0067_jpg_start, (size_t)(frame0067_jpg_end - frame0067_jpg_start) },
    { frame0068_jpg_start, (size_t)(frame0068_jpg_end - frame0068_jpg_start) },
    { frame0069_jpg_start, (size_t)(frame0069_jpg_end - frame0069_jpg_start) },
    { frame0070_jpg_start, (size_t)(frame0070_jpg_end - frame0070_jpg_start) },
    { frame0071_jpg_start, (size_t)(frame0071_jpg_end - frame0071_jpg_start) },
    { frame0072_jpg_start, (size_t)(frame0072_jpg_end - frame0072_jpg_start) },
    { frame0073_jpg_start, (size_t)(frame0073_jpg_end - frame0073_jpg_start) },
    { frame0074_jpg_start, (size_t)(frame0074_jpg_end - frame0074_jpg_start) },
    { frame0075_jpg_start, (size_t)(frame0075_jpg_end - frame0075_jpg_start) },
    { frame0076_jpg_start, (size_t)(frame0076_jpg_end - frame0076_jpg_start) },
    { frame0077_jpg_start, (size_t)(frame0077_jpg_end - frame0077_jpg_start) },
    { frame0078_jpg_start, (size_t)(frame0078_jpg_end - frame0078_jpg_start) },
    { frame0079_jpg_start, (size_t)(frame0079_jpg_end - frame0079_jpg_start) },
    { frame0080_jpg_start, (size_t)(frame0080_jpg_end - frame0080_jpg_start) },
};
