#!/usr/bin/env python3
"""Regenerates the boot animation frame set + main/display/boot_anim_data.h
from assets/boot_anim_source.mp4.

The badge has no video decoder and a tiny 320x240 SPI display, so "playing
the video" means: extract it as a low-fps JPEG flipbook (small enough to
compile in), decode one frame at a time at runtime with the espressif/
esp_jpeg component (ESP32-S3 has TJpgDec in ROM), and blit each decoded
RGB565 frame straight to the display. See boot.cpp's playBootAnimation()
for the playback side.

Frames are embedded via ESP-IDF's EMBED_FILES mechanism (raw linked binary
blobs, not C hex-literal arrays) -- see main/CMakeLists.txt's EMBED_FILES
line, which globs everything this script writes into main/boot_anim_frames/.
This script only regenerates the small header of extern declarations + a
lookup table; it does not touch CMakeLists.txt (that glob is already
in place and picks up whatever frame files exist there).

Usage: python3 tools/gen_boot_anim.py [--fps 8] [--quality 5]
"""
import argparse
import pathlib
import shutil
import subprocess

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE.parent / "assets" / "boot_anim_source.mp4"
FRAMES_DIR = HERE.parent / "main" / "boot_anim_frames"
HEADER = HERE.parent / "main" / "display" / "boot_anim_data.h"

WIDTH, HEIGHT = 320, 240


def symbol_name(rel_path: str) -> str:
    """Mirrors ESP-IDF's EMBED_FILES symbol-name rule: every non-alnum
    character in the (relative) path string becomes an underscore, prefixed
    with _binary_ and suffixed with _start/_end."""
    return "".join(c if c.isalnum() else "_" for c in rel_path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fps", type=int, default=8)
    ap.add_argument("--quality", type=int, default=5, help="ffmpeg -q:v (2=best, 31=worst)")
    args = ap.parse_args()

    if FRAMES_DIR.exists():
        shutil.rmtree(FRAMES_DIR)
    FRAMES_DIR.mkdir(parents=True)

    # Source is 1280x720 (16:9); target is 320x240 (4:3), a narrower aspect
    # ratio -- letterboxing (fit-to-width + pad top/bottom with black bars)
    # was the previous approach here, but on the actual 320x240 panel that
    # reads as "the video doesn't fill/fit the screen" (a visibly small
    # 320x180 strip with black bars above and below), which is exactly what
    # was reported as broken. Switched to cover-and-crop instead:
    # force_original_aspect_ratio=increase scales so BOTH dimensions are at
    # least the target size (here: height-bound, ~427x240), then crop takes
    # the centered 320x240 -- fills the entire panel edge-to-edge with no
    # bars, at the cost of losing the leftmost/rightmost ~50px of the source
    # (acceptable for a boot animation; the source's subject matter -- logo/
    # stars -- is centered per its generation prompt).
    vf = (f"fps={args.fps},"
          f"scale=w={WIDTH}:h={HEIGHT}:force_original_aspect_ratio=increase:flags=lanczos,"
          f"crop={WIDTH}:{HEIGHT}")

    subprocess.run(
        ["ffmpeg", "-y", "-i", str(SRC), "-vf", vf, "-q:v", str(args.quality),
         str(FRAMES_DIR / "frame%04d.jpg")],
        check=True, capture_output=True,
    )

    frame_files = sorted(FRAMES_DIR.glob("frame*.jpg"))
    if not frame_files:
        raise SystemExit("ffmpeg produced no frames")

    total_bytes = sum(f.stat().st_size for f in frame_files)
    print(f"{len(frame_files)} frames, {total_bytes / 1024:.1f} KB total, "
          f"{args.fps} fps ({len(frame_files) / args.fps:.1f}s)")

    lines = []
    lines.append("#pragma once")
    lines.append("// Auto-generated by tools/gen_boot_anim.py from")
    lines.append("// assets/boot_anim_source.mp4 -- do not hand-edit.")
    lines.append("//")
    lines.append("// Frame bytes themselves are NOT in this file -- they're linked in")
    lines.append("// directly from main/boot_anim_frames/*.jpg via EMBED_FILES in")
    lines.append("// main/CMakeLists.txt (raw binary blobs, not C hex arrays, so this")
    lines.append("// header stays tiny regardless of how much frame data there is).")
    lines.append("#include <cstdint>")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append('extern "C" {')
    for f in frame_files:
        sym = symbol_name(f.name)
        lines.append(f'extern const uint8_t {sym}_start[] asm("_binary_{sym}_start");')
        lines.append(f'extern const uint8_t {sym}_end[]   asm("_binary_{sym}_end");')
    lines.append("}")
    lines.append("")
    lines.append("struct BootAnimFrame { const uint8_t* data; size_t len; };")
    lines.append("")
    lines.append(f"constexpr int BOOT_ANIM_FRAME_COUNT = {len(frame_files)};")
    lines.append(f"constexpr int BOOT_ANIM_FPS = {args.fps};")
    lines.append("")
    # NOT constexpr: these addresses come from the linker (EMBED_FILES'
    # _binary_..._start/_end symbols), only known at link time, not
    # compile time -- a plain `const` global with static initialization is
    # correct here and is still zero-runtime-cost (resolved once at
    # startup via the data segment's relocation, not re-evaluated).
    lines.append("const BootAnimFrame BOOT_ANIM_FRAMES[BOOT_ANIM_FRAME_COUNT] = {")
    for f in frame_files:
        sym = symbol_name(f.name)
        lines.append(f"    {{ {sym}_start, (size_t)({sym}_end - {sym}_start) }},")
    lines.append("};")
    lines.append("")

    HEADER.write_text("\n".join(lines))
    print(f"Wrote {HEADER}")


if __name__ == "__main__":
    main()
